name: colorcontact
description: Lista de Contactos

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:

  - assets/

  fonts:

  # Agregamos las fuentes que vamos a utilizar en el proyecto
  # Se utilizara toda la tipografia de la familia Cera

  - family: Cera Black

    fonts:
    - asset: assets/fonts/Cera Pro Black.otf
    - asset: assets/fonts/Cera Pro Black Italic.otf
      style: italic

  - family: Cera Bold

    fonts:
    - asset: assets/fonts/Cera Pro Bold.otf
    - asset: assets/fonts/Cera Pro Bold Italic.otf
      style: italic

  - family: Cera Medium

    fonts:
    - asset: assets/fonts/Cera Pro Medium.otf
    - asset: assets/fonts/Cera Pro Medium Italic.otf
      style: italic

  - family: Cera Regular

    fonts:
    - asset: assets/fonts/Cera Pro Regular.otf
    - asset: assets/fonts/Cera Pro Regular Italic.otf
      style: italic

  - family: Cera Light

    fonts:
    - asset: assets/fonts/Cera Pro Light.otf
    - asset: assets/fonts/Cera Pro Light Italic.otf
      style: italic

  - family: Cera Thin

    fonts:
    - asset: assets/fonts/Cera Pro Thin.otf
    - asset: assets/fonts/Cera Pro Thin Italic.otf
      style: italic